version: 3.1 # Config version

debug: false # Enable debug mode (for developers)
delete-blocks-when-disable: false # Delete blocks created by the plugin when the server is disabled?
delete-game-if-owner-leave: false # Delete game if owner is leave from the server
teleport-player-in-place: true # Teleport the player to the built block?
center-direction-in-teleport: true # Center the player's viewing direction when teleporting?
spawn-display-texts: true # Enables spawning of display texts around blocks (can cause high server load)
allow-destroy-any-block: false # Allow breaking blocks by paths (DANGEROUS FOR THE WORLD!! BLOCKS CANNOT BE RESTORED)
spawn-place-particle: true # Spawn place particles
enable-requests: true # Send an invite to the game instead of adding it at the beginning
immediately-end-game: true # If false, the game will not be removed from the game pool, and the blocks will remain. To delete a game, you can use /deletegame [gamename]
max-requests-size: 10 # Max number of requests to game

max-blocks-for-game: 100
min-blocks-for-game: 5

# Limits in commands
min-symbol-in-answer: 2
max-symbol-in-answer: 20
min-symbol-in-question: 5
max-symbol-in-question: 200

# Limits in creategame command
min-length-path: 4
max-length-path: 200

# Sector for winner firework
# For flicker and trail see https://helpch.at/docs/1.19.4/org/bukkit/FireworkEffect.Builder.html
# For effect type see https://helpch.at/docs/1.19.4/org/bukkit/FireworkEffect.Type.html
end-game-winner-firework:
    enable: true # Enable firework for winner.
    flicker: true # Set whether the firework effect should flicker.
    trail: true # Set whether the firework effect should have a trail.
    type: STAR # The type or shape of the effect.
    colors: [[255, 165, 0], [255, 255, 0]] # (RGB) Add several primary colors to the firework effect.
    fades: [[128, 0, 128]] # (RGB) Add several fade colors to the firework effect.

# Data base section
database:
    enable: false # enable using database
    username: root # username for database account
    password: # password for database account
    host: localhost # host of database (ip)
    port: 3306 # port of database
    database: QAPlugin # database name for plugin

# What to do if the block cannot be broken (paths cannot continue to be built because the block cannot be broken)
# END_GAME the game will simply end, and winners will be calculated (not recommended)
# IGNORE the game will continue, but the bridge where blocks cannot be broken will break
indestructible-block-encountered: IGNORE

# Block names can be found here: https://helpch.at/docs/1.19.4/org/bukkit/Material.html
enabled-blocks: [CYAN_CONCRETE, LIME_CONCRETE, YELLOW_CONCRETE, PURPLE_CONCRETE, BLUE_CONCRETE]

# Sound list available here: https://helpch.at/docs/1.19.4/org/bukkit/Sound.html
win-sound: ENTITY_PLAYER_LEVELUP # Sound played when a player wins
block-place-sound: BLOCK_SCAFFOLDING_PLACE # Sound played when a block is placed

build-delay: 0 # Delay before building starts (in ticks)
build-period: 10 # Building period (in ticks)

# Particles can be found here: https://helpch.at/docs/1.19.4/org/bukkit/Particle.html
place-particle: SPIT # Particle with spawned in player location
particle-count: 1 # Count the number of particles

# Message templates
question-template: "§6Question§8: §f§r{0}" # {0} - question text
questions-are-over: "§cQuestions are over." # Notification that questions are finished

# Plugin messages
game-finished: "§cGame finished."
you-entered-long-path-length: "§cYou have entered too long a path length. {0}/{1}" # {0} entered {1} need
you-entered-short-path-length: "§cYou have entered a path length that is too short. {0}/{1}"
request-success-denied: "§aThe request was successfully rejected."
no-args: "§cNot enough arguments in the command"
you-not-connected-to-game: "§cYou are not connected to a game"
game-is-not-started: "§cThe game has not started yet"
already-answer: "§cYou have already answered this question"
you-answer: "§fYou answered §6{0}" # {0} - player's answer
player-answer: "§fPlayer §6{0} §fanswered" # {0} - player's name
you-dont-have-game-requests: "§cYou have no game requests"
this-game-is-not-requested-you: "§cYou were not invited to this game"
you-connected-to: "§fYou are connected to game §6{0}" # {0} - game name
command-only-for-player: "§cThis command is only available for players"
in-argument-needed-number: "§cThe argument must be a number"
game-is-created: "§aGame created successfully! Now create paths for the players."
is-game-already-created: "§cA game with this name already exists!"
game-not-found: "§cA game with this name was not found"
game-delete: "§aGame deleted"
you-dont-game-owner: "§cYou are not the owner of this game"
is-game-owner: "§cThis is the game owner"
is-player-is-not-found: "§cPlayer not found"
you-have-new-game-requests: "§fYou have a new game invitation! Use §6/acceptgame {0} §fto accept it."
is-command-only-for-game-owner: "§cThis command is only for the game owner"
in-the-game-not-found-paths: "§cNo paths are defined for this game"
players-win-game: "§6{0} §fwon!" # {0} - winner's name
player-win-game: "§6{0} §fwon the game §6{1}!" # {0} - winner's name, {1} - game name
game-add-player-already-started: "§cCannot add a player, the game has already started."
path-created: "§aPath set successfully"
player-accepted-requests: "§fPlayer §6{0} §fhas accepted your invitation!"
requests-sended: "§fRequest to join the game sent to player §6{0}." # {0} - recipient's name
you-already-create-your-game: "§cYou have already created your game, delete the previous one."
not-have-permission: "§cYou do not have permission to use this command."
unknown-error: "§cAn unknown error occurred while executing the command."
many-game-requests: "§cYou have too many game requests. Please ask someone else to join the game"
plugin-success-reloaded: "§aPlugin successfuly reloaded"
inputed-invalid-data: "§cYou have entered incorrect information, check the documentation."
player-does-not-have-layers: "§cThe player does not have enough layers required."
player-dead-and-lose: "§fPlayer §6{0} §f dies, and §close!"
you-dead-and-lose: "§cYou died and lost!"
player-drop-points-with-already-answer: "§fthe player §6{0} §clost his points, §fbecause he answered with a repeating answer!"
command-dont-support-gamemode: "§cThis type of game is not supported by this command"

# {0} - minimum symbols required
# {1} - number of input symbols
in-input-data-little-symbols: "§cYour input has too few symbols! Minimum required: {0}. You input: {1} symbols"

# {0} - maximum symbols allowed
# {1} - number of input symbols
in-input-data-over-symbols: "§cYour input has too many symbols! Maximum allowed: {0}. You input: {1} symbols"

# Your questions
questions:
 - I am the beginning of everything, the end of everything, and the beginning of every ending.
 - I am always hungry, I must always be fed, the touch of me will destroy even the strongest thing.
 - I speak without a mouth and hear without ears. I have no body, but I come alive with wind.
 - I am as light as a feather, but the strongest person cannot hold me for five minutes.
 - I grow up and at the same time I decrease.
 - I am bought to eat, but never eaten.
 - I am full of holes, but I still hold water.
 - The more there is of me, the less you see.
 - I am something that belongs to you, but others use me more than you do.
 - I am what you throw away when you want to use me.
 - I only move when killed.
 - I know the answer, but I don't ask the questions.
 - I cannot be seen, but I can be felt. I can be cruel and I can be gentle.
 - I can be big or small, but you cannot use me until you break me.
 - I have cities, mountains, and water, but no houses, trees, or fish.
 - I have eyes, but I cannot see.
 - I am made of wood, but I am not wood.
 - I live, but never breathe, I move, but never walk.
 - I am always in front of you, but you cannot see me.
 - I fall, but I don't break.
 - I speak, but I have no voice.
 - The more you take from me, the bigger I become.
 - I can be long or short, but I have no beginning and no end.
 - I am always coming, but never arrive.
 - What can fill a room but takes up no space?
 - I am broken when I am not yet formed.
 - I am always near, but I cannot be touched.
 - The more you know about me, the more you forget.
 - I am always growing, but never get taller.
 - I am something people often look for, but rarely find.