name: QAPlugin
api-version: 1.19
description: Adds a question and answer mechanic to your server!
version: 0.4.8
author: Kredwi
main: ru.kredwi.qa.QAPlugin
website: https://github.com/Kredwi/QAPlugin
commands:
  question:
    description: Ask your question.
    usage: /question <question...>
    permission: qaplugin.commands.question
  answer:
    description: Answer the current question.
    usage: /answer <answer>
    permission: qaplugin.commands.answer
  path:
    description: Set the path for a player in the game.
    usage: /path <game name> <player name>
    permission: qaplugin.commands.path
  acceptgame:
    description: Accept the invitation and join the game.
    usage: /acceptgame <game name>
    permission: qaplugin.commands.acceptgame
  denygame:
    description: Deny game request.
    usage: /denygame <game name>
    permission: qaplugin.commands.acceptgame
  creategame:
    description: Create a new game.
    usage: /creategame <game name> <blocks to end>
    permission: qaplugin.commands.creategame
  startgame:
    description: Start the game.
    usage: /startgame <game name>
    permission: qaplugin.commands.startgame
  deletegame:
    description: Delete an existing game.
    usage: /deletegame <game name>
    permission: qaplugin.commands.deletegame
  deleteplayer:
    description: Remove a player from the game.
    usage: /deleteplayer <game name> <player name>
    permission: qaplugin.commands.deleteplayer
permissions:
  qaplugin.commands.answer:
    description: Allows players to answer questions.
    default: true
  qaplugin.commands.question:
    description: Allows players to ask questions.
    default: op
  qaplugin.commands.creategame:
    description: Allows players to create games.
    default: op
  qaplugin.commands.path:
    description: Allows players to set paths.
    default: op
  qaplugin.commands.acceptgame:
    description: Allows players to accept game invitations.
    default: true
  qaplugin.commands.startgame:
    description: Allows players to start games.
    default: op
  qaplugin.commands.deletegame:
    description: Allows players to delete games.
    default: op
  qaplugin.commands.deleteplayer:
    description: Allows players to remove players from games.
    default: op
  qaplugin.*:
    description: Grants all admin permissions for MyPlugin.
    default: op
