name: QAPlugin
api-version: 1.19
description: Adds a question and answer mechanic to your server!
version: 0.6.8
author: Kredwi
main: ru.kredwi.qa.QAPlugin
website: https://github.com/Kredwi/QAPlugin
commands:
  question:
    description: Ask your question.
    usage: /question <question...>
    permission: qaplugin.game.creator
  answer:
    description: Answer the current question.
    usage: /answer <answer>
    permission: qaplugin.game.base
  path:
    description: Set the path for a player in the game.
    usage: /path <game name> <player name>
    permission: qaplugin.game.creator
  acceptgame:
    description: Accept the invitation and join the game.
    usage: /acceptgame <game name>
    permission: qaplugin.game.base
  denygame:
    description: Deny game request.
    usage: /denygame <game name>
    permission: qaplugin.game.base
  creategame:
    description: Create a new game.
    usage: /creategame <game name> <blocks to end>
    permission: qaplugin.game.creator
  startgame:
    description: Start the game.
    usage: /startgame <game name>
    permission: qaplugin.game.creator
  deletegame:
    description: Delete an existing game.
    usage: /deletegame <game name>
    permission: qaplugin.game.creator
  deleteplayer:
    description: Remove a player from the game.
    usage: /deleteplayer <game name> <player name>
    permission: qaplugin.game.creator
  deleteblock:
    description: Delete layers from the path for Player
    usage: /deleteblock <game name>
    permission: qaplugin.game.creator
  qareload:
    description: Reload plugin configuratin.
    usage: /qareload
    permission: qaplugin.plugin.base
permissions:
  qaplugin.game.base:
    description: Basic commands for players
    default: true
  qaplugin.game.creator:
    description: Basic commands for game management
    default: op
    children:
        qaplugin.game.base: true
  qaplugin.plugin.base:
    description: Basic commands for plugin management
    default: op
    children:
        qaplugin.game.base: true
        qaplugin.game.creator: true
  qaplugin.*:
    description: Full access to all plugin commands
    default: op
    children:
        qaplugin.game.base: true
        qaplugin.game.creator: true
        qaplugin.plugin.base: true